services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      SUPABASE_URL: "your-supabase-url"
      SUPABASE_KEY: "your-supabase-key"
    depends_on:
      - qdrant
  qdrant:
    image: qdrant/qdrant:v1.8.3
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
    expose:
      - 6333
    volumes:
      - ./qdrant_data:/qdrant/storage
